SELECT *
FROM customer;

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT
    SUM(purchase_amount) AS total_revenue,
    gender
FROM customer
GROUP BY gender
ORDER BY total_revenue DESC;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT
    customer_id,
    purchase_amount
FROM customer
WHERE
    discount_applied = 'Yes'
    AND purchase_amount >= (
        SELECT AVG(purchase_amount)
        FROM customer
    );

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT
    item_purchased,
    ROUND(CAST(AVG(review_rating) AS NUMERIC), 2) AS avg_product_rating
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Q4. Compare the average purchase amounts between Standard and Express Shipping.
SELECT
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS avg_product_amount
FROM customer
WHERE
    shipping_type = 'Standard'
    OR shipping_type = 'Express'
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue
-- between subscribers and non-subscribers.
SELECT
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT
    item_purchased,
    CONCAT(
        SUM(
            CASE
                WHEN discount_applied = 'Yes' THEN 1
                ELSE 0
            END
        ) * 100 / COUNT(*),
        '%'
    ) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases,
-- and show the count of each segment.
WITH customer_type AS (
    SELECT
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)
SELECT
    customer_segment,
    COUNT(*) AS total_customers
FROM customer_type
GROUP BY customer_segment
ORDER BY total_customers;

-- Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT
    rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT
    COUNT(customer_id) AS repeat_buyers,
    subscription_status
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group?
SELECT
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;